Repository wiredashio/wiredash-sdk, pull requests merged in 2020-05, with the labels that each got.

#16 Floating Entry Point
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/assets/images/logo_draw.png
  lib/assets/images/logo_footer.png
  lib/assets/images/logo_grey.png
  lib/assets/images/logo_white.png
  lib/src/capture/drawer/drawer.dart
  lib/src/common/options/wiredash_options.dart
  lib/src/common/options/wiredash_options_data.dart
  lib/src/common/widgets/dismissible_page_route.dart
  lib/src/common/widgets/floating_entry_point.dart
  lib/src/feedback/components/success_component.dart
  lib/src/feedback/feedback_model.dart
  lib/src/feedback/feedback_sheet.dart
  lib/src/wiredash_controller.dart
  lib/src/wiredash_widget.dart
  lib/wiredash.dart
  pubspec.yaml
Labels: Feature Request, sdk

#17 Updated Sample App
  example/lib/main.dart
Labels: documentation

#19 Pass build info together with feedback
  CHANGELOG.md
  README.md
  example/lib/main.dart
  example/pubspec.lock
  lib/src/common/build_info/build_info_manager.dart
  lib/src/common/user/user_manager.dart
  lib/src/common/utils/build_info.dart
  lib/src/common/utils/device_info.dart
  lib/src/feedback/feedback_model.dart
  lib/src/wiredash_controller.dart
  lib/src/wiredash_widget.dart
  pubspec.yaml
  test/device_info_test.dart
  test/wiredash_widget_test.dart
Labels: feature request, sdk
